const DUNGEON_MASTER = {
  meadow: {
    key: "meadow",
    name: "はじまりの草原",
    desc: "初級向け。素早い小型モンスターが多い。",
    rec: "Lv 1+",
    unlockLevel: 1,
    finalStage: 10,
    bossKey: "KingSlime",
    enemyKeys: ["slime", "rabbitWolf", "goblinScout", "bee", "hornRat"],
    hpScale: 1.35,
    atkScale: 1.3,
    speedScale: 1.16,
    expScale: 1.12,
    goldScale: 1.08,
    lootScale: 1.0,
  },
  cave: {
    key: "cave",
    name: "こだま洞窟",
    desc: "中級向け。体力の高い敵と重い武器が出やすい。",
    rec: "Lv 6+",
    unlockLevel: 6,
    finalStage: 10,
    bossKey: "StoneTitan",
    enemyKeys: [
      "bat",
      "rockLizard",
      "skeletonWarrior",
      "orcRaider",
      "rockGolem",
    ],
    hpScale: 1.92,
    atkScale: 1.68,
    speedScale: 1.08,
    expScale: 1.5,
    goldScale: 1.35,
    lootScale: 1.1,
  },
  ruins: {
    key: "ruins",
    name: "忘却の遺跡",
    desc: "古代兵器と呪いの罠が残る石造遺跡。",
    rec: "Lv 12+",
    unlockLevel: 12,
    finalStage: 10,
    bossKey: "AncientGuard",
    enemyKeys: [
      "cursedArmor",
      "graveMage",
      "stoneSentinel",
      "scarabSwarm",
      "boneArcher",
    ],
    hpScale: 2.5,
    atkScale: 2.2,
    speedScale: 1.1,
    expScale: 2.0,
    goldScale: 1.7,
    lootScale: 1.22,
  },
  forest: {
    key: "forest",
    name: "宵闇の森",
    desc: "毒と奇襲を得意とする獣人が群れる危険地帯。",
    rec: "Lv 18+",
    unlockLevel: 18,
    finalStage: 10,
    bossKey: "NightFang",
    enemyKeys: [
      "shadowPanther",
      "venomBoar",
      "mossTroll",
      "witchOwl",
      "thornDryad",
    ],
    hpScale: 3.2,
    atkScale: 2.85,
    speedScale: 1.16,
    expScale: 2.45,
    goldScale: 2.05,
    lootScale: 1.35,
  },
  volcano: {
    key: "volcano",
    name: "灼熱火山",
    desc: "高火力の魔物が押し寄せる、耐久力試しの火口域。",
    rec: "Lv 25+",
    unlockLevel: 25,
    finalStage: 10,
    bossKey: "MagmaHydra",
    enemyKeys: [
      "lavaImp",
      "ashWyvern",
      "flameKnight",
      "emberSpirit",
      "obsidianBeast",
    ],
    hpScale: 4.1,
    atkScale: 3.55,
    speedScale: 1.2,
    expScale: 2.95,
    goldScale: 2.45,
    lootScale: 1.5,
  },
  citadel: {
    key: "citadel",
    name: "鉄壁の要塞",
    desc: "重装兵だらけの堅牢な要塞。高防御を崩せる火力が必要。",
    rec: "Lv 33+",
    unlockLevel: 33,
    finalStage: 10,
    bossKey: "IronGeneral",
    enemyKeys: [
      "ironGuard",
      "crossbowTurret",
      "warPriest",
      "siegeOgre",
      "steelJuggernaut",
    ],
    hpScale: 5.2,
    atkScale: 4.35,
    speedScale: 1.23,
    expScale: 3.55,
    goldScale: 2.95,
    lootScale: 1.68,
  },
  abyss: {
    key: "abyss",
    name: "深淵回廊",
    desc: "闇属性の猛攻と吸収攻撃が続く長大な回廊。",
    rec: "Lv 42+",
    unlockLevel: 42,
    finalStage: 10,
    bossKey: "AbyssReaper",
    enemyKeys: [
      "voidMantis",
      "gloomSpecter",
      "bloodLeech",
      "doomKnight",
      "nightmareHound",
    ],
    hpScale: 6.5,
    atkScale: 5.35,
    speedScale: 1.28,
    expScale: 4.2,
    goldScale: 3.6,
    lootScale: 1.9,
  },
  sky: {
    key: "sky",
    name: "天穹神殿",
    desc: "空中戦が主体。回避と瞬間火力の両立が試される。",
    rec: "Lv 52+",
    unlockLevel: 52,
    finalStage: 10,
    bossKey: "StormSeraph",
    enemyKeys: [
      "thunderRoc",
      "aeroSentinel",
      "skyTemplar",
      "lightningSprite",
      "cloudGiant",
    ],
    hpScale: 8.1,
    atkScale: 6.6,
    speedScale: 1.34,
    expScale: 4.95,
    goldScale: 4.35,
    lootScale: 2.15,
  },
  void: {
    key: "void",
    name: "虚無領域",
    desc: "空間の歪みで常識外れの攻撃が飛び交う終盤ダンジョン。",
    rec: "Lv 63+",
    unlockLevel: 63,
    finalStage: 10,
    bossKey: "VoidDragon",
    enemyKeys: [
      "riftStalker",
      "entropyWisp",
      "cosmicGolem",
      "nullAssassin",
      "starDevourer",
    ],
    hpScale: 10.2,
    atkScale: 8.2,
    speedScale: 1.4,
    expScale: 5.8,
    goldScale: 5.2,
    lootScale: 2.45,
  },
  throne: {
    key: "throne",
    name: "終焉の玉座",
    desc: "全てを越えた者だけが辿り着く、最終決戦の間。",
    rec: "Lv 75+",
    unlockLevel: 75,
    finalStage: 10,
    bossKey: "EndKing",
    enemyKeys: [
      "royalExecutioner",
      "chaosOracle",
      "eternalGuardian",
      "doomHarbinger",
      "fateBreaker",
    ],
    hpScale: 12.8,
    atkScale: 10.0,
    speedScale: 1.46,
    expScale: 6.8,
    goldScale: 6.0,
    lootScale: 2.8,
  },
};
