const DUNGEON_MASTER = {
  meadow: {
    key: "meadow",
    name: "はじまりの草原",
    desc: "初級向け。素早い小型モンスターが多い。",
    rec: "Lv 1+",
    unlockLevel: 1,
    finalStage: 10,
    bossKey: "KingSlime",
    enemyKeys: ["slime", "rabbitWolf", "Goblin", "bee", "hornRat"],
    hpScale: 1.4,
    atkScale: 1.35,
    speedScale: 1.18,
    expScale: 1.15,
    goldScale: 1.1,
  },
  cave: {
    key: "cave",
    name: "こだま洞窟",
    desc: "中級向け。体力の高い敵と重い武器が出やすい。",
    rec: "Lv 6+",
    unlockLevel: 6,
    finalStage: 10,
    bossKey: "StoneTitan",
    enemyKeys: ["Bat", "rockLizard", "skeletonWarrior", "Orc", "rockGolem"],
    hpScale: 1.95,
    atkScale: 1.65,
    speedScale: 1.05,
    expScale: 1.55,
    goldScale: 1.4,
  },
};
