const ENEMY_MASTER = {
  slime: {
    key: "slime",
    name: "スライム",
    hp: 36,
    atk: 7,
    attackInterval: 1.45,
    exp: 7,
    gold: 6,
  },
  rabbitWolf: {
    key: "rabbitWolf",
    name: "ウサギオオカミ",
    hp: 42,
    atk: 8,
    attackInterval: 1.15,
    exp: 8,
    gold: 7,
  },
  Goblin: {
    key: "Goblin",
    name: "ゴブリン",
    hp: 52,
    atk: 9,
    attackInterval: 1.3,
    exp: 9,
    gold: 8,
  },
  bee: {
    key: "bee",
    name: "ハチ",
    hp: 28,
    atk: 7,
    attackInterval: 0.9,
    exp: 7,
    gold: 6,
  },
  hornRat: {
    key: "hornRat",
    name: "角ネズミ",
    hp: 34,
    atk: 8,
    attackInterval: 1.02,
    exp: 7,
    gold: 6,
  },
  Bat: {
    key: "Bat",
    name: "コウモリ",
    hp: 40,
    atk: 10,
    attackInterval: 0.88,
    exp: 10,
    gold: 8,
  },
  rockLizard: {
    key: "rockLizard",
    name: "岩トカゲ",
    hp: 56,
    atk: 12,
    attackInterval: 1.12,
    exp: 12,
    gold: 10,
  },
  skeletonWarrior: {
    key: "skeletonWarrior",
    name: "骨戦士",
    hp: 64,
    atk: 14,
    attackInterval: 1.25,
    exp: 14,
    gold: 12,
  },
  Orc: {
    key: "Orc",
    name: "オーク",
    hp: 78,
    atk: 16,
    attackInterval: 1.35,
    exp: 16,
    gold: 14,
  },
  rockGolem: {
    key: "rockGolem",
    name: "岩ゴーレム",
    hp: 98,
    atk: 18,
    attackInterval: 1.55,
    exp: 18,
    gold: 16,
  },
};

const BOSS_MASTER = {
  KingSlime: {
    key: "KingSlime",
    name: "キングスライム",
    hp: 240,
    atk: 28,
    attackInterval: 1.6,
    exp: 42,
    gold: 38,
  },
  StoneTitan: {
    key: "StoneTitan",
    name: "ストーンタイタン",
    hp: 420,
    atk: 42,
    attackInterval: 1.8,
    exp: 72,
    gold: 66,
  },
};
