const ENEMY_MASTER = {
  slime: {
    key: "slime",
    name: "スライム",
    hp: 44,
    atk: 9,
    attackInterval: 1.45,
    exp: 7,
    gold: 6,
  },
  rabbitWolf: {
    key: "rabbitWolf",
    name: "ウサギオオカミ",
    hp: 50,
    atk: 10,
    attackInterval: 1.15,
    exp: 8,
    gold: 7,
  },
  goblinScout: {
    key: "goblinScout",
    name: "ゴブリン斥候",
    hp: 60,
    atk: 11,
    attackInterval: 1.24,
    exp: 9,
    gold: 8,
  },
  bee: {
    key: "bee",
    name: "ハチ",
    hp: 34,
    atk: 9,
    attackInterval: 0.9,
    exp: 7,
    gold: 6,
  },
  hornRat: {
    key: "hornRat",
    name: "角ネズミ",
    hp: 41,
    atk: 10,
    attackInterval: 1.02,
    exp: 7,
    gold: 6,
  },

  bat: {
    key: "bat",
    name: "コウモリ",
    hp: 40,
    atk: 10,
    attackInterval: 0.88,
    exp: 10,
    gold: 8,
  },
  rockLizard: {
    key: "rockLizard",
    name: "岩トカゲ",
    hp: 56,
    atk: 12,
    attackInterval: 1.12,
    exp: 12,
    gold: 10,
  },
  skeletonWarrior: {
    key: "skeletonWarrior",
    name: "骨戦士",
    hp: 64,
    atk: 14,
    attackInterval: 1.25,
    exp: 14,
    gold: 12,
  },
  orcRaider: {
    key: "orcRaider",
    name: "オーク略奪兵",
    hp: 78,
    atk: 16,
    attackInterval: 1.35,
    exp: 16,
    gold: 14,
  },
  rockGolem: {
    key: "rockGolem",
    name: "岩ゴーレム",
    hp: 98,
    atk: 18,
    attackInterval: 1.55,
    exp: 18,
    gold: 16,
  },

  cursedArmor: { key: "cursedArmor", name: "呪鎧", hp: 118, atk: 22, attackInterval: 1.42, exp: 24, gold: 20 },
  graveMage: { key: "graveMage", name: "墓所の魔導士", hp: 92, atk: 27, attackInterval: 1.18, exp: 25, gold: 22 },
  stoneSentinel: { key: "stoneSentinel", name: "石像兵", hp: 136, atk: 23, attackInterval: 1.5, exp: 25, gold: 21 },
  scarabSwarm: { key: "scarabSwarm", name: "スカラベ群", hp: 84, atk: 20, attackInterval: 0.86, exp: 23, gold: 20 },
  boneArcher: { key: "boneArcher", name: "ボーンアーチャー", hp: 96, atk: 25, attackInterval: 1.06, exp: 24, gold: 21 },

  shadowPanther: { key: "shadowPanther", name: "影豹", hp: 122, atk: 29, attackInterval: 1.0, exp: 30, gold: 27 },
  venomBoar: { key: "venomBoar", name: "毒牙イノシシ", hp: 164, atk: 27, attackInterval: 1.32, exp: 31, gold: 28 },
  mossTroll: { key: "mossTroll", name: "苔トロル", hp: 186, atk: 30, attackInterval: 1.48, exp: 33, gold: 29 },
  witchOwl: { key: "witchOwl", name: "魔梟", hp: 114, atk: 32, attackInterval: 0.94, exp: 32, gold: 30 },
  thornDryad: { key: "thornDryad", name: "茨ドライアド", hp: 146, atk: 31, attackInterval: 1.2, exp: 32, gold: 29 },

  lavaImp: { key: "lavaImp", name: "ラヴァインプ", hp: 168, atk: 36, attackInterval: 0.96, exp: 39, gold: 36 },
  ashWyvern: { key: "ashWyvern", name: "灰翼ワイバーン", hp: 214, atk: 37, attackInterval: 1.22, exp: 41, gold: 38 },
  flameKnight: { key: "flameKnight", name: "炎騎士", hp: 238, atk: 40, attackInterval: 1.34, exp: 43, gold: 39 },
  emberSpirit: { key: "emberSpirit", name: "残火の精", hp: 154, atk: 38, attackInterval: 0.84, exp: 40, gold: 37 },
  obsidianBeast: { key: "obsidianBeast", name: "黒曜獣", hp: 266, atk: 41, attackInterval: 1.4, exp: 44, gold: 40 },

  ironGuard: { key: "ironGuard", name: "鉄衛兵", hp: 282, atk: 45, attackInterval: 1.3, exp: 49, gold: 46 },
  crossbowTurret: { key: "crossbowTurret", name: "連弩砲台", hp: 226, atk: 48, attackInterval: 0.92, exp: 50, gold: 47 },
  warPriest: { key: "warPriest", name: "戦祈祷師", hp: 246, atk: 50, attackInterval: 1.05, exp: 52, gold: 49 },
  siegeOgre: { key: "siegeOgre", name: "攻城オーガ", hp: 324, atk: 46, attackInterval: 1.55, exp: 52, gold: 48 },
  steelJuggernaut: { key: "steelJuggernaut", name: "鋼装ジャガーノート", hp: 348, atk: 49, attackInterval: 1.46, exp: 54, gold: 50 },

  voidMantis: { key: "voidMantis", name: "虚刃カマキリ", hp: 310, atk: 56, attackInterval: 0.9, exp: 60, gold: 58 },
  gloomSpecter: { key: "gloomSpecter", name: "幽冥スペクター", hp: 258, atk: 61, attackInterval: 1.02, exp: 62, gold: 60 },
  bloodLeech: { key: "bloodLeech", name: "血喰らい", hp: 336, atk: 55, attackInterval: 1.18, exp: 61, gold: 59 },
  doomKnight: { key: "doomKnight", name: "終焉騎士", hp: 372, atk: 58, attackInterval: 1.3, exp: 64, gold: 61 },
  nightmareHound: { key: "nightmareHound", name: "悪夢の猟犬", hp: 286, atk: 60, attackInterval: 0.96, exp: 63, gold: 60 },

  thunderRoc: { key: "thunderRoc", name: "雷鳥ロック", hp: 372, atk: 66, attackInterval: 1.02, exp: 72, gold: 72 },
  aeroSentinel: { key: "aeroSentinel", name: "風護センチネル", hp: 398, atk: 64, attackInterval: 1.14, exp: 73, gold: 73 },
  skyTemplar: { key: "skyTemplar", name: "蒼穹聖堂騎士", hp: 430, atk: 68, attackInterval: 1.2, exp: 75, gold: 75 },
  lightningSprite: { key: "lightningSprite", name: "稲妻妖精", hp: 302, atk: 69, attackInterval: 0.78, exp: 72, gold: 71 },
  cloudGiant: { key: "cloudGiant", name: "雲巨人", hp: 474, atk: 67, attackInterval: 1.36, exp: 76, gold: 76 },

  riftStalker: { key: "riftStalker", name: "裂界ストーカー", hp: 468, atk: 76, attackInterval: 0.98, exp: 86, gold: 86 },
  entropyWisp: { key: "entropyWisp", name: "崩壊ウィスプ", hp: 344, atk: 80, attackInterval: 0.72, exp: 85, gold: 85 },
  cosmicGolem: { key: "cosmicGolem", name: "星核ゴーレム", hp: 532, atk: 75, attackInterval: 1.3, exp: 88, gold: 88 },
  nullAssassin: { key: "nullAssassin", name: "ヌルアサシン", hp: 392, atk: 82, attackInterval: 0.88, exp: 87, gold: 87 },
  starDevourer: { key: "starDevourer", name: "星喰い", hp: 566, atk: 78, attackInterval: 1.24, exp: 90, gold: 90 },

  royalExecutioner: { key: "royalExecutioner", name: "王命処刑人", hp: 598, atk: 86, attackInterval: 1.04, exp: 98, gold: 100 },
  chaosOracle: { key: "chaosOracle", name: "混沌の託宣者", hp: 462, atk: 92, attackInterval: 0.8, exp: 99, gold: 101 },
  eternalGuardian: { key: "eternalGuardian", name: "永劫守護兵", hp: 654, atk: 84, attackInterval: 1.38, exp: 101, gold: 102 },
  doomHarbinger: { key: "doomHarbinger", name: "破滅の前触れ", hp: 524, atk: 90, attackInterval: 0.9, exp: 100, gold: 101 },
  fateBreaker: { key: "fateBreaker", name: "運命破り", hp: 612, atk: 88, attackInterval: 1.12, exp: 102, gold: 103 },
};

const BOSS_MASTER = {
  KingSlime: {
    key: "KingSlime",
    name: "キングスライム",
    hp: 240,
    atk: 28,
    attackInterval: 1.6,
    exp: 42,
    gold: 38,
  },
  StoneTitan: {
    key: "StoneTitan",
    name: "ストーンタイタン",
    hp: 420,
    atk: 42,
    attackInterval: 1.8,
    exp: 72,
    gold: 66,
  },
  AncientGuard: {
    key: "AncientGuard",
    name: "古代守護者アグノス",
    hp: 690,
    atk: 58,
    attackInterval: 1.68,
    exp: 122,
    gold: 112,
  },
  NightFang: {
    key: "NightFang",
    name: "宵闇王ナイトファング",
    hp: 980,
    atk: 78,
    attackInterval: 1.52,
    exp: 182,
    gold: 168,
  },
  MagmaHydra: {
    key: "MagmaHydra",
    name: "灼熱ヒュドラ",
    hp: 1320,
    atk: 102,
    attackInterval: 1.45,
    exp: 252,
    gold: 236,
  },
  IronGeneral: {
    key: "IronGeneral",
    name: "鉄壁将軍バルガス",
    hp: 1780,
    atk: 132,
    attackInterval: 1.5,
    exp: 338,
    gold: 320,
  },
  AbyssReaper: {
    key: "AbyssReaper",
    name: "深淵刈りアビスリーパー",
    hp: 2380,
    atk: 170,
    attackInterval: 1.42,
    exp: 446,
    gold: 425,
  },
  StormSeraph: {
    key: "StormSeraph",
    name: "嵐天使セラフ",
    hp: 3120,
    atk: 214,
    attackInterval: 1.34,
    exp: 582,
    gold: 560,
  },
  VoidDragon: {
    key: "VoidDragon",
    name: "虚竜ヴォイドドラゴン",
    hp: 4120,
    atk: 270,
    attackInterval: 1.28,
    exp: 742,
    gold: 724,
  },
  EndKing: {
    key: "EndKing",
    name: "終焉王エンドキング",
    hp: 5480,
    atk: 336,
    attackInterval: 1.22,
    exp: 946,
    gold: 920,
  },
};
