const weaponBases = [
  // 剣 (tier 0-10)
  { name: "ショートソード", weaponType: "剣", minAtk: 4, maxAtk: 8, attackInterval: 1.0, minTier: 0 },
  { name: "ロングソード", weaponType: "剣", minAtk: 6, maxAtk: 10, attackInterval: 1.02, minTier: 1 },
  { name: "ブロードソード", weaponType: "剣", minAtk: 8, maxAtk: 13, attackInterval: 1.04, minTier: 2 },
  { name: "騎士剣", weaponType: "剣", minAtk: 10, maxAtk: 16, attackInterval: 1.06, minTier: 3 },
  { name: "ルーンブレード", weaponType: "剣", minAtk: 12, maxAtk: 19, attackInterval: 1.08, minTier: 4 },
  { name: "王国騎士の剣", weaponType: "剣", minAtk: 14, maxAtk: 22, attackInterval: 1.1, minTier: 5 },
  { name: "王者の剣", weaponType: "剣", minAtk: 17, maxAtk: 26, attackInterval: 1.12, minTier: 6 },
  { name: "覇刃グローリア", weaponType: "剣", minAtk: 20, maxAtk: 30, attackInterval: 1.14, minTier: 7 },
  { name: "天光の聖剣", weaponType: "剣", minAtk: 23, maxAtk: 34, attackInterval: 1.16, minTier: 8 },
  { name: "覇王剣グランデ", weaponType: "剣", minAtk: 26, maxAtk: 38, attackInterval: 1.18, minTier: 9 },
  { name: "神話の聖剣", weaponType: "剣", minAtk: 30, maxAtk: 43, attackInterval: 1.2, minTier: 10 },

  // 斧 (tier 0-10)
  { name: "バトルアクス", weaponType: "斧", minAtk: 7, maxAtk: 12, attackInterval: 2.0, minTier: 0 },
  { name: "ヘビーアクス", weaponType: "斧", minAtk: 9, maxAtk: 15, attackInterval: 1.96, minTier: 1 },
  { name: "ウォーアクス", weaponType: "斧", minAtk: 11, maxAtk: 18, attackInterval: 1.92, minTier: 2 },
  { name: "グレートアクス", weaponType: "斧", minAtk: 13, maxAtk: 21, attackInterval: 1.88, minTier: 3 },
  { name: "処刑人の斧", weaponType: "斧", minAtk: 15, maxAtk: 24, attackInterval: 1.84, minTier: 4 },
  { name: "断岩の戦斧", weaponType: "斧", minAtk: 18, maxAtk: 28, attackInterval: 1.8, minTier: 5 },
  { name: "断罪の斧", weaponType: "斧", minAtk: 21, maxAtk: 32, attackInterval: 1.76, minTier: 6 },
  { name: "巨獣狩りの斧", weaponType: "斧", minAtk: 24, maxAtk: 36, attackInterval: 1.72, minTier: 7 },
  { name: "震天の巨斧", weaponType: "斧", minAtk: 27, maxAtk: 40, attackInterval: 1.68, minTier: 8 },
  { name: "地砕きの巨斧", weaponType: "斧", minAtk: 30, maxAtk: 44, attackInterval: 1.64, minTier: 9 },
  { name: "世界樹の戦斧", weaponType: "斧", minAtk: 34, maxAtk: 49, attackInterval: 1.6, minTier: 10 },

  // 短剣 (tier 0-10)
  { name: "ダガー", weaponType: "短剣", minAtk: 3, maxAtk: 6, attackInterval: 0.8, minTier: 0 },
  { name: "ツインダガー", weaponType: "短剣", minAtk: 5, maxAtk: 9, attackInterval: 0.78, minTier: 1 },
  { name: "盗賊の短剣", weaponType: "短剣", minAtk: 7, maxAtk: 12, attackInterval: 0.76, minTier: 2 },
  { name: "疾風の短剣", weaponType: "短剣", minAtk: 9, maxAtk: 15, attackInterval: 0.74, minTier: 3 },
  { name: "影縫いの短剣", weaponType: "短剣", minAtk: 11, maxAtk: 18, attackInterval: 0.72, minTier: 4 },
  { name: "霧隠れの刃", weaponType: "短剣", minAtk: 13, maxAtk: 21, attackInterval: 0.7, minTier: 5 },
  { name: "月影の短剣", weaponType: "短剣", minAtk: 15, maxAtk: 24, attackInterval: 0.68, minTier: 6 },
  { name: "星屑の短剣", weaponType: "短剣", minAtk: 18, maxAtk: 28, attackInterval: 0.66, minTier: 7 },
  { name: "夜渡りの双刃", weaponType: "短剣", minAtk: 21, maxAtk: 32, attackInterval: 0.64, minTier: 8 },
  { name: "月影の双刃", weaponType: "短剣", minAtk: 24, maxAtk: 36, attackInterval: 0.62, minTier: 9 },
  { name: "虚空裂きの短剣", weaponType: "短剣", minAtk: 28, maxAtk: 41, attackInterval: 0.6, minTier: 10 },

  // 杖 (tier 0-10)
  { name: "ワンド", weaponType: "杖", minAtk: 3, maxAtk: 7, attackInterval: 1.2, minTier: 0 },
  { name: "オークワンド", weaponType: "杖", minAtk: 5, maxAtk: 10, attackInterval: 1.22, minTier: 1 },
  { name: "ルーンスタッフ", weaponType: "杖", minAtk: 7, maxAtk: 13, attackInterval: 1.24, minTier: 2 },
  { name: "メイジスタッフ", weaponType: "杖", minAtk: 9, maxAtk: 16, attackInterval: 1.26, minTier: 3 },
  { name: "アークスタッフ", weaponType: "杖", minAtk: 11, maxAtk: 19, attackInterval: 1.28, minTier: 4 },
  { name: "賢者の杖", weaponType: "杖", minAtk: 14, maxAtk: 23, attackInterval: 1.3, minTier: 5 },
  { name: "導師の魔杖", weaponType: "杖", minAtk: 17, maxAtk: 27, attackInterval: 1.32, minTier: 6 },
  { name: "深淵の魔杖", weaponType: "杖", minAtk: 20, maxAtk: 31, attackInterval: 1.34, minTier: 7 },
  { name: "星導の大杖", weaponType: "杖", minAtk: 23, maxAtk: 35, attackInterval: 1.36, minTier: 8 },
  { name: "天啓の神杖", weaponType: "杖", minAtk: 26, maxAtk: 39, attackInterval: 1.38, minTier: 9 },
  { name: "根源の神杖", weaponType: "杖", minAtk: 30, maxAtk: 44, attackInterval: 1.4, minTier: 10 },

  // 弓 (tier 0-10)
  { name: "ショートボウ", weaponType: "弓", minAtk: 5, maxAtk: 9, attackInterval: 1.0, minTier: 0 },
  { name: "ハンターボウ", weaponType: "弓", minAtk: 7, maxAtk: 12, attackInterval: 1.02, minTier: 1 },
  { name: "ロングボウ", weaponType: "弓", minAtk: 9, maxAtk: 15, attackInterval: 1.04, minTier: 2 },
  { name: "コンポジットボウ", weaponType: "弓", minAtk: 11, maxAtk: 18, attackInterval: 1.06, minTier: 3 },
  { name: "スナイプボウ", weaponType: "弓", minAtk: 13, maxAtk: 21, attackInterval: 1.08, minTier: 4 },
  { name: "エルフボウ", weaponType: "弓", minAtk: 15, maxAtk: 24, attackInterval: 1.1, minTier: 5 },
  { name: "天穿つ弓", weaponType: "弓", minAtk: 18, maxAtk: 28, attackInterval: 1.12, minTier: 6 },
  { name: "疾空の戦弓", weaponType: "弓", minAtk: 21, maxAtk: 32, attackInterval: 1.14, minTier: 7 },
  { name: "蒼穹の狩弓", weaponType: "弓", minAtk: 24, maxAtk: 36, attackInterval: 1.16, minTier: 8 },
  { name: "星巡りの神弓", weaponType: "弓", minAtk: 27, maxAtk: 40, attackInterval: 1.18, minTier: 9 },
  { name: "彗星穿ちの神弓", weaponType: "弓", minAtk: 31, maxAtk: 45, attackInterval: 1.2, minTier: 10 },
];

const armorBases = [
  { name: "レザーアーマー", minDef: 2, maxDef: 4, hp: 14, minTier: 0 },
  { name: "チェインメイル", minDef: 4, maxDef: 7, hp: 22, minTier: 1 },
  { name: "スケイルアーマー", minDef: 5, maxDef: 8, hp: 26, minTier: 2 },
  { name: "ミスリルアーマー", minDef: 6, maxDef: 10, hp: 30, minTier: 3 },
  { name: "プレートアーマー", minDef: 8, maxDef: 12, hp: 36, minTier: 4 },
  { name: "聖騎士の鎧", minDef: 9, maxDef: 13, hp: 40, minTier: 5 },
  { name: "ドラゴンスキン", minDef: 10, maxDef: 15, hp: 44, minTier: 6 },
  { name: "深淵装甲", minDef: 12, maxDef: 18, hp: 52, minTier: 7 },
  { name: "天穹の神鎧", minDef: 14, maxDef: 21, hp: 60, minTier: 8 },
  { name: "終焉の甲冑", minDef: 16, maxDef: 24, hp: 70, minTier: 9 },
  { name: "星界の重鎧", minDef: 18, maxDef: 27, hp: 80, minTier: 11 },
  { name: "創世の神鎧", minDef: 21, maxDef: 31, hp: 92, minTier: 13 },
  { name: "ローブ", minDef: 1, maxDef: 3, hp: 10, minTier: 0 },
];

const accessoryBases = [
  { name: "生命の指輪", hp: 22, vit: 2, minTier: 0 },
  { name: "俊足のお守り", agi: 4, def: 1, minTier: 0 },
  { name: "守護のペンダント", vit: 3, def: 1, hp: 8, minTier: 0 },
  { name: "戦士の紋章", str: 3, hp: 10, minTier: 1 },
  { name: "猛攻のブローチ", str: 5, atk: 4, minTier: 2 },
  { name: "賢者のタリスマン", vit: 4, hp: 20, def: 2, minTier: 3 },
  { name: "疾風の羽飾り", agi: 6, def: 2, minTier: 4 },
  { name: "不滅の護符", hp: 38, vit: 5, def: 3, minTier: 5 },
  { name: "覇王の印章", str: 7, hp: 16, def: 2, minTier: 6 },
  { name: "奈落の宝珠", atk: 8, str: 8, hp: 24, minTier: 7 },
  { name: "天空の加護", hp: 48, vit: 7, agi: 4, def: 4, minTier: 8 },
  { name: "終焉の紋環", atk: 10, str: 10, vit: 8, hp: 30, def: 5, minTier: 9 },
  { name: "流星の王印", atk: 13, str: 12, agi: 8, hp: 36, def: 6, minTier: 11 },
  { name: "万象の聖環", atk: 16, str: 14, vit: 12, hp: 48, def: 8, minTier: 13 },
];
