const weaponBases = [
  // 剣 (tier 0-10)
  {
    name: "ショートソード",
    weaponType: "剣",
    minAtk: 5,
    maxAtk: 9,
    attackInterval: 1.0,
    minTier: 0,
  },
  {
    name: "ロングソード",
    weaponType: "剣",
    minAtk: 7,
    maxAtk: 12,
    attackInterval: 1.0,
    minTier: 1,
  },
  {
    name: "ブロードソード",
    weaponType: "剣",
    minAtk: 9,
    maxAtk: 15,
    attackInterval: 1.0,
    minTier: 2,
  },
  {
    name: "騎士剣",
    weaponType: "剣",
    minAtk: 11,
    maxAtk: 18,
    attackInterval: 1.0,
    minTier: 3,
  },
  {
    name: "ルーンブレード",
    weaponType: "剣",
    minAtk: 13,
    maxAtk: 21,
    attackInterval: 1.0,
    minTier: 4,
  },
  {
    name: "王国騎士の剣",
    weaponType: "剣",
    minAtk: 15,
    maxAtk: 24,
    attackInterval: 1.0,
    minTier: 5,
  },
  {
    name: "王者の剣",
    weaponType: "剣",
    minAtk: 17,
    maxAtk: 27,
    attackInterval: 1.0,
    minTier: 6,
  },
  {
    name: "覇刃グローリア",
    weaponType: "剣",
    minAtk: 19,
    maxAtk: 30,
    attackInterval: 1.0,
    minTier: 7,
  },
  {
    name: "天光の聖剣",
    weaponType: "剣",
    minAtk: 21,
    maxAtk: 33,
    attackInterval: 1.0,
    minTier: 8,
  },
  {
    name: "覇王剣グランデ",
    weaponType: "剣",
    minAtk: 23,
    maxAtk: 36,
    attackInterval: 1.0,
    minTier: 9,
  },
  {
    name: "神話の聖剣",
    weaponType: "剣",
    minAtk: 25,
    maxAtk: 39,
    attackInterval: 1.0,
    minTier: 10,
  },

  // 斧 (tier 0-10)
  {
    name: "バトルアクス",
    weaponType: "斧",
    minAtk: 10,
    maxAtk: 16,
    attackInterval: 2.0,
    minTier: 0,
  },
  {
    name: "ヘビーアクス",
    weaponType: "斧",
    minAtk: 14,
    maxAtk: 21,
    attackInterval: 2.0,
    minTier: 1,
  },
  {
    name: "ウォーアクス",
    weaponType: "斧",
    minAtk: 18,
    maxAtk: 26,
    attackInterval: 2.0,
    minTier: 2,
  },
  {
    name: "グレートアクス",
    weaponType: "斧",
    minAtk: 22,
    maxAtk: 31,
    attackInterval: 2.0,
    minTier: 3,
  },
  {
    name: "処刑人の斧",
    weaponType: "斧",
    minAtk: 26,
    maxAtk: 36,
    attackInterval: 2.0,
    minTier: 4,
  },
  {
    name: "断岩の戦斧",
    weaponType: "斧",
    minAtk: 30,
    maxAtk: 41,
    attackInterval: 2.0,
    minTier: 5,
  },
  {
    name: "断罪の斧",
    weaponType: "斧",
    minAtk: 34,
    maxAtk: 46,
    attackInterval: 2.0,
    minTier: 6,
  },
  {
    name: "巨獣狩りの斧",
    weaponType: "斧",
    minAtk: 38,
    maxAtk: 51,
    attackInterval: 2.0,
    minTier: 7,
  },
  {
    name: "震天の巨斧",
    weaponType: "斧",
    minAtk: 42,
    maxAtk: 56,
    attackInterval: 2.0,
    minTier: 8,
  },
  {
    name: "地砕きの巨斧",
    weaponType: "斧",
    minAtk: 46,
    maxAtk: 61,
    attackInterval: 2.0,
    minTier: 9,
  },
  {
    name: "世界樹の戦斧",
    weaponType: "斧",
    minAtk: 50,
    maxAtk: 66,
    attackInterval: 2.0,
    minTier: 10,
  },

  // 短剣 (tier 0-10)
  {
    name: "ダガー",
    weaponType: "短剣",
    minAtk: 3,
    maxAtk: 6,
    attackInterval: 0.8,
    minTier: 0,
  },
  {
    name: "ツインダガー",
    weaponType: "短剣",
    minAtk: 5,
    maxAtk: 9,
    attackInterval: 0.8,
    minTier: 1,
  },
  {
    name: "盗賊の短剣",
    weaponType: "短剣",
    minAtk: 7,
    maxAtk: 12,
    attackInterval: 0.8,
    minTier: 2,
  },
  {
    name: "疾風の短剣",
    weaponType: "短剣",
    minAtk: 9,
    maxAtk: 15,
    attackInterval: 0.8,
    minTier: 3,
  },
  {
    name: "影縫いの短剣",
    weaponType: "短剣",
    minAtk: 11,
    maxAtk: 18,
    attackInterval: 0.8,
    minTier: 4,
  },
  {
    name: "霧隠れの刃",
    weaponType: "短剣",
    minAtk: 13,
    maxAtk: 21,
    attackInterval: 0.8,
    minTier: 5,
  },
  {
    name: "月影の短剣",
    weaponType: "短剣",
    minAtk: 15,
    maxAtk: 24,
    attackInterval: 0.8,
    minTier: 6,
  },
  {
    name: "星屑の短剣",
    weaponType: "短剣",
    minAtk: 17,
    maxAtk: 27,
    attackInterval: 0.8,
    minTier: 7,
  },
  {
    name: "夜渡りの双刃",
    weaponType: "短剣",
    minAtk: 19,
    maxAtk: 30,
    attackInterval: 0.8,
    minTier: 8,
  },
  {
    name: "月影の双刃",
    weaponType: "短剣",
    minAtk: 21,
    maxAtk: 33,
    attackInterval: 0.8,
    minTier: 9,
  },
  {
    name: "虚空裂きの短剣",
    weaponType: "短剣",
    minAtk: 23,
    maxAtk: 36,
    attackInterval: 0.8,
    minTier: 10,
  },

  // 杖 (tier 0-10)
  {
    name: "ワンド",
    weaponType: "杖",
    minAtk: 7,
    maxAtk: 12,
    attackInterval: 1.3,
    minTier: 0,
  },
  {
    name: "オークワンド",
    weaponType: "杖",
    minAtk: 10,
    maxAtk: 16,
    attackInterval: 1.3,
    minTier: 1,
  },
  {
    name: "ルーンスタッフ",
    weaponType: "杖",
    minAtk: 13,
    maxAtk: 20,
    attackInterval: 1.3,
    minTier: 2,
  },
  {
    name: "メイジスタッフ",
    weaponType: "杖",
    minAtk: 16,
    maxAtk: 24,
    attackInterval: 1.3,
    minTier: 3,
  },
  {
    name: "アークスタッフ",
    weaponType: "杖",
    minAtk: 19,
    maxAtk: 28,
    attackInterval: 1.3,
    minTier: 4,
  },
  {
    name: "賢者の杖",
    weaponType: "杖",
    minAtk: 22,
    maxAtk: 32,
    attackInterval: 1.3,
    minTier: 5,
  },
  {
    name: "導師の魔杖",
    weaponType: "杖",
    minAtk: 25,
    maxAtk: 36,
    attackInterval: 1.3,
    minTier: 6,
  },
  {
    name: "深淵の魔杖",
    weaponType: "杖",
    minAtk: 28,
    maxAtk: 40,
    attackInterval: 1.3,
    minTier: 7,
  },
  {
    name: "星導の大杖",
    weaponType: "杖",
    minAtk: 31,
    maxAtk: 44,
    attackInterval: 1.3,
    minTier: 8,
  },
  {
    name: "天啓の神杖",
    weaponType: "杖",
    minAtk: 34,
    maxAtk: 48,
    attackInterval: 1.3,
    minTier: 9,
  },
  {
    name: "根源の神杖",
    weaponType: "杖",
    minAtk: 37,
    maxAtk: 52,
    attackInterval: 1.3,
    minTier: 10,
  },

  // 弓 (tier 0-10)
  {
    name: "ショートボウ",
    weaponType: "弓",
    minAtk: 6,
    maxAtk: 10,
    attackInterval: 1.1,
    minTier: 0,
  },
  {
    name: "ハンターボウ",
    weaponType: "弓",
    minAtk: 8,
    maxAtk: 13,
    attackInterval: 1.1,
    minTier: 1,
  },
  {
    name: "ロングボウ",
    weaponType: "弓",
    minAtk: 10,
    maxAtk: 16,
    attackInterval: 1.1,
    minTier: 2,
  },
  {
    name: "コンポジットボウ",
    weaponType: "弓",
    minAtk: 12,
    maxAtk: 19,
    attackInterval: 1.1,
    minTier: 3,
  },
  {
    name: "スナイプボウ",
    weaponType: "弓",
    minAtk: 14,
    maxAtk: 22,
    attackInterval: 1.1,
    minTier: 4,
  },
  {
    name: "エルフボウ",
    weaponType: "弓",
    minAtk: 16,
    maxAtk: 25,
    attackInterval: 1.1,
    minTier: 5,
  },
  {
    name: "天穿つ弓",
    weaponType: "弓",
    minAtk: 18,
    maxAtk: 28,
    attackInterval: 1.1,
    minTier: 6,
  },
  {
    name: "疾空の戦弓",
    weaponType: "弓",
    minAtk: 20,
    maxAtk: 31,
    attackInterval: 1.1,
    minTier: 7,
  },
  {
    name: "蒼穹の狩弓",
    weaponType: "弓",
    minAtk: 22,
    maxAtk: 34,
    attackInterval: 1.1,
    minTier: 8,
  },
  {
    name: "星巡りの神弓",
    weaponType: "弓",
    minAtk: 24,
    maxAtk: 37,
    attackInterval: 1.1,
    minTier: 9,
  },
  {
    name: "彗星穿ちの神弓",
    weaponType: "弓",
    minAtk: 26,
    maxAtk: 40,
    attackInterval: 1.1,
    minTier: 10,
  },
];
const armorBases = [
  { name: "レザーアーマー", minDef: 2, maxDef: 4, hp: 14, minTier: 0 },
  { name: "チェインメイル", minDef: 3, maxDef: 6, hp: 20, minTier: 1 },
  { name: "スケイルアーマー", minDef: 5, maxDef: 8, hp: 26, minTier: 2 },
  { name: "ミスリルアーマー", minDef: 6, maxDef: 10, hp: 32, minTier: 3 },
  { name: "プレートアーマー", minDef: 8, maxDef: 12, hp: 38, minTier: 4 },
  { name: "聖騎士の鎧", minDef: 10, maxDef: 14, hp: 44, minTier: 5 },
  { name: "ドラゴンスキン", minDef: 12, maxDef: 17, hp: 50, minTier: 6 },
  { name: "深淵装甲", minDef: 14, maxDef: 20, hp: 58, minTier: 7 },
  { name: "天穹の神鎧", minDef: 16, maxDef: 23, hp: 66, minTier: 8 },
  { name: "終焉の甲冑", minDef: 19, maxDef: 27, hp: 75, minTier: 9 },
  { name: "創世の神鎧", minDef: 22, maxDef: 31, hp: 86, minTier: 10 },
];

const accessoryBases = [
  { name: "生命の指輪", hp: 22, vit: 2, minTier: 0 },
  { name: "俊足のお守り", agi: 4, def: 1, hp: 8, minTier: 1 },
  { name: "守護のペンダント", vit: 3, def: 2, hp: 12, minTier: 2 },
  { name: "戦士の紋章", str: 4, atk: 2, hp: 14, minTier: 3 },
  { name: "猛攻のブローチ", str: 6, atk: 5, hp: 18, minTier: 4 },
  { name: "賢者のタリスマン", vit: 6, hp: 28, def: 3, minTier: 5 },
  { name: "疾風の羽飾り", agi: 8, def: 3, hp: 24, minTier: 6 },
  { name: "不滅の護符", hp: 42, vit: 8, def: 4, minTier: 7 },
  { name: "覇王の印章", str: 10, atk: 8, hp: 30, def: 4, minTier: 8 },
  { name: "終焉の紋環", atk: 12, str: 12, vit: 10, hp: 38, def: 5, minTier: 9 },
  {
    name: "万象の聖環",
    atk: 15,
    str: 14,
    vit: 12,
    agi: 8,
    hp: 48,
    def: 7,
    minTier: 10,
  },
];
