const weaponBases = [
  {
    name: "ショートソード",
    weaponType: "剣",
    minAtk: 4,
    maxAtk: 8,
    attackInterval: 1.0,
    minTier: 0,
  },
  {
    name: "ロングソード",
    weaponType: "剣",
    minAtk: 7,
    maxAtk: 12,
    attackInterval: 1.05,
    minTier: 1,
  },
  {
    name: "騎士剣",
    weaponType: "剣",
    minAtk: 11,
    maxAtk: 17,
    attackInterval: 1.1,
    minTier: 3,
  },
  {
    name: "王者の剣",
    weaponType: "剣",
    minAtk: 16,
    maxAtk: 24,
    attackInterval: 1.12,
    minTier: 6,
  },

  {
    name: "バトルアクス",
    weaponType: "斧",
    minAtk: 7,
    maxAtk: 12,
    attackInterval: 2.0,
    minTier: 0,
  },
  {
    name: "ヘビーアクス",
    weaponType: "斧",
    minAtk: 11,
    maxAtk: 17,
    attackInterval: 1.9,
    minTier: 2,
  },
  {
    name: "グレートアクス",
    weaponType: "斧",
    minAtk: 15,
    maxAtk: 23,
    attackInterval: 1.85,
    minTier: 4,
  },
  {
    name: "断罪の斧",
    weaponType: "斧",
    minAtk: 20,
    maxAtk: 30,
    attackInterval: 1.8,
    minTier: 7,
  },

  {
    name: "ダガー",
    weaponType: "短剣",
    minAtk: 3,
    maxAtk: 6,
    attackInterval: 0.8,
    minTier: 0,
  },
  {
    name: "ツインダガー",
    weaponType: "短剣",
    minAtk: 6,
    maxAtk: 10,
    attackInterval: 0.72,
    minTier: 1,
  },
  {
    name: "影縫いの短剣",
    weaponType: "短剣",
    minAtk: 10,
    maxAtk: 15,
    attackInterval: 0.7,
    minTier: 4,
  },
  {
    name: "星屑の短剣",
    weaponType: "短剣",
    minAtk: 14,
    maxAtk: 22,
    attackInterval: 0.68,
    minTier: 7,
  },

  {
    name: "ワンド",
    weaponType: "杖",
    minAtk: 3,
    maxAtk: 7,
    attackInterval: 1.2,
    minTier: 0,
  },
  {
    name: "ルーンスタッフ",
    weaponType: "杖",
    minAtk: 8,
    maxAtk: 14,
    attackInterval: 1.3,
    minTier: 2,
  },
  {
    name: "賢者の杖",
    weaponType: "杖",
    minAtk: 13,
    maxAtk: 20,
    attackInterval: 1.32,
    minTier: 5,
  },
  {
    name: "深淵の魔杖",
    weaponType: "杖",
    minAtk: 18,
    maxAtk: 27,
    attackInterval: 1.35,
    minTier: 8,
  },

  {
    name: "ショートボウ",
    weaponType: "弓",
    minAtk: 5,
    maxAtk: 9,
    attackInterval: 1.0,
    minTier: 0,
  },
  {
    name: "ロングボウ",
    weaponType: "弓",
    minAtk: 9,
    maxAtk: 14,
    attackInterval: 1.05,
    minTier: 2,
  },
  {
    name: "コンポジットボウ",
    weaponType: "弓",
    minAtk: 14,
    maxAtk: 21,
    attackInterval: 1.08,
    minTier: 5,
  },
  {
    name: "天穿つ弓",
    weaponType: "弓",
    minAtk: 19,
    maxAtk: 29,
    attackInterval: 1.1,
    minTier: 8,
  },
];

const armorBases = [
  { name: "レザーアーマー", minDef: 2, maxDef: 4, hp: 14, minTier: 0 },
  { name: "チェインメイル", minDef: 4, maxDef: 7, hp: 22, minTier: 1 },
  { name: "スケイルアーマー", minDef: 5, maxDef: 8, hp: 26, minTier: 2 },
  { name: "ミスリルアーマー", minDef: 6, maxDef: 10, hp: 30, minTier: 3 },
  { name: "プレートアーマー", minDef: 8, maxDef: 12, hp: 36, minTier: 4 },
  { name: "聖騎士の鎧", minDef: 9, maxDef: 13, hp: 40, minTier: 5 },
  { name: "ドラゴンスキン", minDef: 10, maxDef: 15, hp: 44, minTier: 6 },
  { name: "深淵装甲", minDef: 12, maxDef: 18, hp: 52, minTier: 7 },
  { name: "天穹の神鎧", minDef: 14, maxDef: 21, hp: 60, minTier: 8 },
  { name: "終焉の甲冑", minDef: 16, maxDef: 24, hp: 70, minTier: 9 },
  { name: "ローブ", minDef: 1, maxDef: 3, hp: 10, minTier: 0 },
];

const accessoryBases = [
  { name: "生命の指輪", hp: 22, vit: 2, minTier: 0 },
  { name: "俊足のお守り", agi: 4, def: 1, minTier: 0 },
  { name: "守護のペンダント", vit: 3, def: 1, hp: 8, minTier: 0 },
  { name: "戦士の紋章", str: 3, hp: 10, minTier: 1 },
  { name: "猛攻のブローチ", str: 5, atk: 4, minTier: 2 },
  { name: "賢者のタリスマン", vit: 4, hp: 20, def: 2, minTier: 3 },
  { name: "疾風の羽飾り", agi: 6, def: 2, minTier: 4 },
  { name: "不滅の護符", hp: 38, vit: 5, def: 3, minTier: 5 },
  { name: "覇王の印章", str: 7, hp: 16, def: 2, minTier: 6 },
  { name: "奈落の宝珠", atk: 8, str: 8, hp: 24, minTier: 7 },
  { name: "天空の加護", hp: 48, vit: 7, agi: 4, def: 4, minTier: 8 },
  { name: "終焉の紋環", atk: 10, str: 10, vit: 8, hp: 30, def: 5, minTier: 9 },
];
